# Generated by Django 4.1.2 on 2022-11-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date_released', models.DateField(help_text='year-month-date', null=True)),
                ('likes', models.CharField(max_length=400)),
                ('artiste_id', models.CharField(blank=True, max_length=40, null=True)),
                ('Artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text="Enter Lyric's of the song", max_length=1000)),
                ('song_id', models.CharField(blank=True, max_length=40, null=True)),
                ('Artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
                ('Song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
            ],
        ),
    ]
