# Generated by Django 4.1.2 on 2022-10-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Song_id',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='lyric',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='Artist_id',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default='null'),
        ),
    ]
