# Generated by Django 4.1.2 on 2022-10-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artist_id',
        ),
    ]
