# Generated by Django 4.1.2 on 2022-10-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_artiste_id_song_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
    ]
