# Generated by Django 4.1.2 on 2022-10-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_song_id_lyric_artiste_lyric_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Artist_id',
            new_name='Artist_Id',
        ),
    ]
