# Generated by Django 4.1.2 on 2022-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_song_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artiste_id',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
