# Generated by Django 4.1.2 on 2022-10-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_rename_song_id_lyric_songid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='Songid',
        ),
    ]
