# Generated by Django 4.1.2 on 2022-10-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_remove_lyric_songid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Songid',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
