# Generated by Django 4.1.2 on 2022-10-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_lyric_songid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Songid',
            new_name='Song_id',
        ),
    ]
