# Generated by Django 4.1.2 on 2022-10-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_rename_songid_lyric_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='Song_id',
        ),
    ]
