# Generated by Django 4.1.2 on 2022-11-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_rename_artiste_id_song_artiste_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Artiste_id',
        ),
        migrations.AddField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
