# Generated by Django 4.1.2 on 2022-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_remove_lyric_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Songid',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
