# Generated by Django 4.1.2 on 2022-10-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_lyric_songid_alter_lyric_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artistid',
            new_name='artist_id',
        ),
    ]
