# Generated by Django 4.1.2 on 2022-10-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_rename_artistid_song_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Songid',
            new_name='Song_id',
        ),
    ]
